---
# Elasticsearch configuration
elasticsearch_cluster_name: "infra-project"
elasticsearch_node_name: "elasticsearch-01"
elasticsearch_network_host: "0.0.0.0"
elasticsearch_http_port: 9200
elasticsearch_discovery_type: "single-node"

# JVM settings
elasticsearch_jvm_options:
  - "-Xms1g"
  - "-Xmx1g"

# Index settings
elasticsearch_indices:
  - name: "nginx-logs-*"
    template: "nginx-logs-template"
